const data =[
    {
        new:'New',
        name:'iPhone 14 Pro Max',
        img:'https://i.postimg.cc/kGDm0FZq/iphone14-Pro-Card.jpg',
        price:1099,
        id:101,
        color1:'deepPurple circle',
        color2:'gold circle',
        color3:'silver circle',
        color4:'graphite circle',
        image1:'https://i.postimg.cc/d15FNS55/iphone14-Pro-1.jpg',
        image2:'https://i.postimg.cc/HnKgd8D5/iphone14-Pro-2-1.jpg',
        image3:'https://i.postimg.cc/44FZzq7d/iphone14-Pro-2-2.jpg',
        category:'iPhone'
    },
    {
        new:'New',
        name:'iPhone 14 Pro',
        img:'https://i.postimg.cc/kGDm0FZq/iphone14-Pro-Card.jpg',
        price:999,
        id:102,
        color1:'deepPurple circle',
        color2:'gold circle',
        color3:'silver circle',
        color4:'graphite circle',
        image1:'https://i.postimg.cc/d15FNS55/iphone14-Pro-1.jpg',
        image2:'https://i.postimg.cc/HnKgd8D5/iphone14-Pro-2-1.jpg',
        image3:'https://i.postimg.cc/MGGvv0zf/iphone14-Pro-2-2.jpg',
        category:'iPhone'
    },
    {
        new:'New',
        name:'iPhone 14',
        img:'https://i.postimg.cc/dVKM6tC6/iphone14-Card.jpg',
        price:799,
        id:103,
        color1:'blue circle',
        color2:'purple circle',
        color3:'graphite circle',
        color4:'silver circle',
        color5:'red circle',
        image1:'https://i.postimg.cc/yYR40SDW/iphone14-1.jpg',
        image2:'https://i.postimg.cc/BvqrWYM1/iphone14-2-1.jpg',
        image3:'https://i.postimg.cc/HkzrYv1C/iphone14-2-2.jpg',
        category:'iPhone'
    },
    {
        new:'',
        name:'iPhone 13 Pro Max',
        img:'https://i.postimg.cc/528gKQjj/i-Phone13-Pro-Max-Card.jpg',
        price:1099,
        id:201,
        color1:'green circle',
        color2:'silver circle',
        color3:'gold circle',
        color4:'graphite circle',
        color5:'blue circle',
        image1:'https://i.postimg.cc/kMY5Ypd2/iPhone1.jpg',
        image2:'https://i.postimg.cc/HxtLXcWC/Iphone2-1.png',
        image3:'https://i.postimg.cc/cC4Lmx6t/i-Phone2-2.png',
        category:'iPhone'
    },
    {
        new:'',
        name:'iPhone 13 Pro',
        img:'https://i.postimg.cc/528gKQjj/i-Phone13-Pro-Max-Card.jpg',
        price:999,
        id:202,
        color1:'green circle',
        color2:'silver circle',
        color3:'gold circle',
        color4:'graphite circle',
        color5:'blue circle',
        image1:'https://i.postimg.cc/kMY5Ypd2/iPhone1.jpg',
        image2:'https://i.postimg.cc/HxtLXcWC/Iphone2-1.png',
        image3:'https://i.postimg.cc/cC4Lmx6t/i-Phone2-2.png',
        category:'iPhone'
    },
    {
        new:'',
        name:'iPhone 13',
        img:'https://i.postimg.cc/4dpwqKWW/i-Phone13-Card.jpg',
        price:699,
        id:203,
        color1:'green circle',
        color2:'graphite circle',
        color3:'pink circle',
        color4:'blue circle',
        color5:'red circle',
        image1:'https://i.postimg.cc/DfJPzKnP/i-Phone13-1.jpg',
        image2:'https://i.postimg.cc/mDvddv7W/i-Phone13-2-1.jpg',
        image3:'https://i.postimg.cc/LsjN0C4c/i-Phone13-2-2.jpg',
        category:'iPhone'
    },
    {
        new:'',
        name:'iPhone 12',
        img:'https://i.postimg.cc/sxFGxhB7/iphone12-Card.jpg',
        price:599,
        id:301,
        color1:'gold circle',
        color2:'purple circle',
        color3:'blue circle',
        color4:'creamGreen circle',
        color5:'graphite circle',
        color6:'red circle',
        image1:'https://i.postimg.cc/TPQm31G3/i-Phone12-1.jpg',
        image2:'https://i.postimg.cc/BZzTFjF8/i-Phone12-2-1.jpg',
        image3:'https://i.postimg.cc/kgfctcPx/iphone12-2-2.jpg',
        category:'iPhone'
    },
    {
        new:'',
        name:'iPhone 12 Mini',
        img:'https://i.postimg.cc/K8YjZN9C/iphone12-Mini-Card.jpg',
        price:499,
        id:302,
        color1:'gold circle',
        color2:'purple circle',
        color3:'blue circle',
        color4:'creamGreen circle',
        color5:'graphite circle',
        color6:'red circle',
        image1:'https://i.postimg.cc/TPQm31G3/i-Phone12-1.jpg',
        image2:'https://i.postimg.cc/BZzTFjF8/i-Phone12-2-1.jpg',
        image3:'https://i.postimg.cc/W1GgxSHr/iphone12-2-2.jpg',
        category:'iPhone',
    },
    {
        new:'',
        name:'iPhone SE 2022',
        img:'https://i.postimg.cc/G24mkm0K/iphone-SE-Card.jpg',
        price:429,
        id:303,
        color1:'graphite circle',
        color2:'silver circle',
        color3:'red circle',
        image1:'https://i.postimg.cc/8CTMGW2Y/iphone-SE-1.jpg',
        image2:'https://i.postimg.cc/TYWrJTjt/iphone-SE-2-1.jpg',
        image3:'https://i.postimg.cc/t4p1HQf5/iphone-SE-2-2.jpg',
        category:'iPhone',
    },

]

export default data;