import iphone12ProMax from '../assets/images/iphone/iPhone12Pro.jpg'
import iphone12 from '../assets/images/iphone/iphone-12.jpg'
import iphone11ProMax from '../assets/images/iphone/iphone11ProMax.jpg';
import iphone11 from '../assets/images/iphone/iphone11.jpg';

const dataIphones =[
    {
        new:'New',
        name:'iPhone 13 Pro Max',
        img:'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-card-40-iphone13pro-202203?wid=340&hei=264&fmt=p-jpg&qlt=95&.v=1644989935267"',
        price:1099,
        id:101,
        color1:'green circle',
        color2:'silver circle',
        color3:'gold circle',
        color4:'graphite circle',
        color5:'blue circle',
    },
    {
        new:'New',
        name:'iPhone 13 Pro',
        img:'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-card-40-iphone13pro-202203?wid=340&hei=264&fmt=p-jpg&qlt=95&.v=1644989935267"',
        price:999,
        id:102,
        color1:'green circle',
        color2:'silver circle',
        color3:'gold circle',
        color4:'graphite circle',
        color5:'blue circle',
    },
    {
        new:'New',
        name:'iPhone 13',
        img:'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-card-40-iphone13-202203?wid=340&hei=264&fmt=p-jpg&qlt=95&.v=1646335268199',
        price:699,
        id:103,
        color1:'green circle',
        color2:'graphite circle',
        color3:'pink circle',
        color4:'blue circle',
        color5:'red circle',
    },
    {
        new:'',
        name:'iPhone 12 Pro Max',
        img:iphone12ProMax,
        price:899,
        id:201,
        color1:'silver circle',
        color2:'graphite circle',
        color3:'gold circle',
        color4:'blue circle',
    },
    {
        new:'',
        name:'iPhone 12 Pro',
        img:iphone12ProMax,
        price:799,
        id:202,
        color1:'silver circle',
        color2:'graphite circle',
        color3:'gold circle',
        color4:'blue circle',
    },
    {
        new:'',
        name:'iPhone 12',
        img:iphone12,
        price:599,
        id:203,
        color1:'gold circle',
        color2:'purple circle',
        color3:'blue circle',
        color4:'creamGreen circle',
        color5:'graphite circle',
        color6:'red circle',
    },
    {
        new:'',
        name:'iPhone 11 Pro Max',
        img:iphone11ProMax,
        price:799,
        id:301,
        color1:'gold circle',
        color2:'graphite circle',
        color3:'silver circle',
        color4:'green circle',
    },
    {
        new:'',
        name:'iPhone 11 Pro',
        img:iphone11ProMax,
        price:699,
        id:302,
        color1:'gold circle',
        color2:'graphite circle',
        color3:'silver circle',
        color4:'green circle',
    },
    {
        new:'',
        name:'iPhone 11',
        img:iphone11,
        price:499,
        id:303,
        color1:'creamGreen circle',
        color2:'purple circle',
        color3:'yellow circle',
        color4:'graphite circle',
        color5:'silver circle',
        color6:'red circle'
    },

]

export default dataIphones;